code cleanup and reorganization of composes

diff --git a/server/containers/rag-server/Dockerfile b/server/containers/rag-server/Dockerfile
--- a/server/containers/rag-server/Dockerfile
+++ b/server/containers/rag-server/Dockerfile
@@ -4,7 +4,8 @@ ARG BASE_IMAGE=ghcr.io/longevity-genie/just-agents/chat-ui-agents:main
 FROM ${BASE_IMAGE}
 
 # Create directory and add requirements
-RUN mkdir -p /app/agent_tools/ /app/env
+RUN mkdir -p /app/agent_tools/ /app/env /app/tmp
+RUN chmod -R 777 /app/tmp /app/env
 ADD server/containers/rag-server/init.py /app/agent_tools/init.py
 ADD server/containers/rag-server/requirements.txt /app/agent_tools/requirements.txt
 RUN ls -la /app/agent_tools/
@@ -13,5 +14,5 @@ RUN poetry remove just-agents-web # we remove local version of just-agents-web b
 RUN bash /usr/local/bin/entrypoint.sh echo "Installing dependencies with the entrypoint!" 2>&1
 
 # Add verification step
-RUN python -c "import torch; print(f'PyTorch version: {torch.__version__}')" || echo "PyTorch not found"
-CMD ["python", "-m", "just_semantic_search.run_rag_server", "run_rag_server_command"]
+RUN python -c "import torch; print(f'PyTorch version: {torch.__version__}')" || echo "PyTorch not found" 2>&1
+CMD ["python", "-m", "just_semantic_search.rag_server", "run_rag_server_command"]
